.TH AEDIT 1 "version 1.1" "December 2023"
.SH NAME
aedit \- a simple text editor
.SH SYNOPSIS
aedit [file]
.SH DESCRIPTION
aedit is a simple text editor inspired by ISIS-II aedit.
.SH EDITING
The program works in a number of modes during editing. A menu is presented showing options at any stage. Use the END key to exit from the Insert or Xchange modes or submenus.
.SH OPTIONS
Pass the name of the file to edit.
.SH SEE ALSO
https://aedit.sf.net
.SH AUTHOR
Roger Brown (rhubarb-geek-nz@users.sourceforge.net)
