#!/bin/sh -e
#
#  Copyright 2021, Roger Brown
#
#  This file is part of RHB aedit
#
#  This program is free software: you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation, either version 3 of the License, or (at your
#  option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# $Id: Darwin 70 2024-01-19 11:24:45Z rhubarb-geek-nz $
#

VERSION=$(grep "Id:\ aedit.c" < src/aedit.c | while read A B C D E; do echo $D; done)
MAJVERS=1
MINVERS=$(echo $VERSION / 256 + 1 | bc)
BLDVERS=$(echo $VERSION % 256 | bc)
PWD=$(pwd)

VERSION="$MAJVERS.$MINVERS.$BLDVERS"
PKGNAME="aedit-$VERSION"

cleanup()
{
	rm -rf bom	
}

trap cleanup 0

cleanup

umask 022

mkdir -p bom/bin bom/share/man/man1
cp aedit bom/bin
gzip < aedit.1 > bom/share/man/man1/aedit.1.gz
pkgbuild --root bom --identifier net.sf.aedit --version "$VERSION" --install-location /usr/local --sign "Developer ID Installer: $APPLE_DEVELOPER" "$PKGNAME.pkg"
