#!/bin/sh -e
#
#  Copyright 2021, Roger Brown
#
#  This file is part of RHB aedit
#
#  This program is free software: you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by the
#  Free Software Foundation, either version 3 of the License, or (at your
#  option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# $Id: Darwin 4 2021-04-18 12:02:33Z rhubarb-geek-nz $
#

VERSION=$(grep "Id:\ aedit.c" < src/aedit.c | while read A B C D E; do echo $D; done)
HIVERS=$(echo $VERSION / 10000 | bc)
LOVERS=$(echo $VERSION % 10000 | bc)
PWD=`pwd`

VERSION="1.1.$HIVERS.$LOVERS"
PKGNAME="aedit-$VERSION"

cleanup()
{
	rm -rf bom	
}

trap cleanup 0

cleanup

mkdir bom
cp aedit bom
pkgbuild --root bom --identifier net.sf.rhbaedit --version "$VERSION" --install-location /usr/local/bin --sign "Developer ID Installer: $APPLE_DEVELOPER" "$PKGNAME.pkg"
