#!/bin/sh -e
#
#  Copyright 2021, Roger Brown
#
#  This file is part of RHB aedit.
#
#  This program is free software: you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation, either version 3 of the License, or (at your
#  option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# $Id: GNU 86 2024-02-05 04:58:19Z rhubarb-geek-nz $
#

cleanup()
{
	rm -rf data rpms rpm.spec
}

umask 022

cleanup

trap cleanup 0

VERSION=$(grep "Id:\ aedit.c" < src/aedit.c | while read A B C D E; do echo $D; done)
MAJVERS=1
MINVERS=$(echo $VERSION / 256 + 1 | bc)
BLDVERS=$(echo $VERSION % 256 | bc)
PWD=$(pwd)
VERSION="$MAJVERS.$MINVERS.$BLDVERS"
PKGNAME=aedit

mkdir -p data/usr/bin rpms "data/usr/share/doc/$PKGNAME" "data/usr/share/man/man1"

cp aedit data/usr/bin

strip data/usr/bin/aedit

sed --quiet < src/aedit.c '/\*\*\*\*/,/^ \*\//p' | grep -v '\*\*\*' | grep -v '^ \*/' | while read A B
do
	echo "$B"
done | ( 
	while read A
	do
		if test -n "$A"
		then
			echo "$A"
			break
		fi
	done
	cat 
) > "data/usr/share/doc/$PKGNAME/copyright"

if git config --get remote.origin.url
then
	(
		set -e
		git config --get remote.origin.url
		TZ=UTC git log --oneline src/aedit.c
	) > "data/usr/share/doc/$PKGNAME/changelog"
else
	if svn info .
	then
		(
			set -e
			svn info . | grep "^URL: " | while read A B
			do
				echo "$B"
			done
			TZ=UTC svn log src/aedit.c
		) > "data/usr/share/doc/$PKGNAME/changelog"
	fi
fi

if test -f "data/usr/share/doc/$PKGNAME/changelog"
then
	gzip "data/usr/share/doc/$PKGNAME/changelog"
fi

gzip < README.md > "data/usr/share/doc/$PKGNAME/README.md.gz"
gzip < aedit.1 > "data/usr/share/man/man1/aedit.1.gz"

if dpkg --print-architecture 2>/dev/null
then
	DPKGARCH=$(dpkg --print-architecture)
	SIZE=$(du -sk data/usr/bin/aedit | while read A B; do echo $A; done)
	mkdir data/DEBIAN
	cat > data/DEBIAN/control <<EOF
Package: $PKGNAME
Version: $VERSION
Architecture: $DPKGARCH
Installed-Size: $SIZE
Maintainer: rhubarb-geek-nz@users.sourceforge.net
Section: editors
Priority: extra
Description: Text Editor based on Intel ISIS-II aedit
 Text editor based on interface from Intel ISIS-II aedit, which in turn was based on its big brother alter.
 This was originally written in the mid 80s on QNX running on an 8088, with a CBM-64 acting as the console.
 .
EOF

	dpkg-deb --root-owner-group --build data "$PKGNAME"_"$VERSION"_"$DPKGARCH".deb

	rm -rf data/DEBIAN
fi

if rpmbuild --version 2>/dev/null
then
	cat > rpm.spec <<EOF
Summary: Aedit editor
Name: aedit
Version: $VERSION
Release: 1
Group: Applications/System
License: GPL
Prefix: /usr

%description
Text editor based on ISIS alter

%files
%defattr(-,root,root)
%attr(755,root,root) /usr/bin/aedit

%clean
EOF

	rpmbuild --buildroot "$PWD/data" --define "_rpmdir $PWD/rpms" --define "_build_id_links none" -bb "$PWD/rpm.spec" 

	find rpms -name "*.rpm" -type f | while read N
	do
		mv "$N" .
	done
fi
