#!/bin/sh -e
#
#  Copyright 2021, Roger Brown
#
#  This file is part of RHB aedit.
#
#  This program is free software: you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation, either version 3 of the License, or (at your
#  option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# $Id: Linux 54 2023-12-20 21:22:08Z rhubarb-geek-nz $
#

cleanup()
{
	rm -rf data rpms rpm.spec
}

umask 022

cleanup

trap cleanup 0

VERSION=$(grep "Id:\ aedit.c" < src/aedit.c | while read A B C D E; do echo $D; done)
HIVERS=$(echo $VERSION / 256 | bc)
LOVERS=$(echo $VERSION % 256 | bc)
PWD=`pwd`
ISSLACK=false
ISRPM=false
ISDEB=false

for d in $( . /etc/os-release ; echo $ID $ID_LIKE )
do
	case "$d" in
		debian )
			ISDEB=true
			;;
		fedora | centos | rhel | mariner | suse | opensuse )
			ISRPM=true
			;;
		slackware )
			ISSLACK=true
			;;
	esac
done

VERSION="1.1.$HIVERS.$LOVERS"
PKGNAME=aedit

mkdir -p data/usr/bin rpms "data/usr/share/doc/$PKGNAME" "data/usr/share/man/man1"

cp aedit data/usr/bin

sed --quiet < src/aedit.c '/\*\*\*\*/,/^ \*\//p' | grep -v '\*\*\*' | grep -v '^ \*/' | while read A B
do
	echo "$B"
done | ( 
	while read A
	do
		if test -n "$A"
		then
			echo "$A"
			break
		fi
	done
	cat 
) > "data/usr/share/doc/$PKGNAME/copyright"

if git config --get remote.origin.url
then
	(
		set -e
		git config --get remote.origin.url
		TZ=UTC git log --oneline src/aedit.c
	) > "data/usr/share/doc/$PKGNAME/changelog"
else
	if svn info .
	then
		(
			set -e
			svn info . | grep "^URL: " | while read A B
			do
				echo "$B"
			done
			TZ=UTC svn log src/aedit.c
		) > "data/usr/share/doc/$PKGNAME/changelog"
	fi
fi

if test -f "data/usr/share/doc/$PKGNAME/changelog"
then
	gzip "data/usr/share/doc/$PKGNAME/changelog"
fi

gzip < README.md > "data/usr/share/doc/$PKGNAME/README.md.gz"
gzip < aedit.1 > "data/usr/share/man/man1/aedit.1.gz"

if $ISDEB
then
	DPKGARCH=$(dpkg --print-architecture)
	SIZE=$(du -sk data/usr/bin/aedit | while read A B; do echo $A; done)
	mkdir data/DEBIAN
	cat > data/DEBIAN/control <<EOF
Package: $PKGNAME
Version: $VERSION
Architecture: $DPKGARCH
Installed-Size: $SIZE
Maintainer: rhubarb-geek-nz@users.sourceforge.net
Section: editors
Priority: extra
Description: Aedit editor
 Text editor based resembling ISIS alter.
 .
EOF

	dpkg-deb --root-owner-group --build data "$PKGNAME"_"$VERSION"_"$DPKGARCH".deb

	rm -rf data/DEBIAN
fi

if $ISRPM
then
	(
		set -e

		cd "$PWD/data"

		cat <<EOF
Summary: Aedit editor
Name: aedit
Version: $VERSION
Release: 1
Group: Applications/System
License: GPL
Prefix: /usr

%description
Text editor based on ISIS alter

%files
%defattr(-,root,root)
%attr(555,root,root) /usr/bin/aedit
%dir %attr(555,root,root) /usr/share/doc/aedit
%attr(444,root,root) /usr/share/doc/aedit/README.md.gz
EOF

		if test -f "usr/share/doc/aedit/changelog.gz"
		then
			cat <<EOF
%attr(444,root,root) /usr/share/doc/aedit/changelog.gz
EOF
		fi

		cat <<EOF
%attr(444,root,root) /usr/share/doc/aedit/copyright
%attr(444,root,root) /usr/share/man/man1/aedit.1.gz

%clean
EOF
	) > rpm.spec

	rpmbuild --buildroot "$PWD/data" --define "_rpmdir $PWD/rpms" --define "_build_id_links none" -bb "$PWD/rpm.spec" 

	find rpms -name "*.rpm" -type f | while read N
	do
		mv "$N" .
	done
fi

if $ISSLACK
then
	mkdir -p data/usr/bin data/install data/root
	cp aedit data/usr/bin
	strip data/usr/bin/aedit

	cat > data/install/slack-desc <<EOF
$PKGNAME: aedit ISIS-II style text editor
$PKGNAME:
$PKGNAME: Text editor based on interface from Intel ISIS-II aedit, which in turn
$PKGNAME: turn was based on its big brother alter. 
$PKGNAME: 
$PKGNAME: This was originally written in the mid 80s on QNX running on an 8088, 
$PKGNAME: with a CBM-64 acting as the console. I have used this on every UNIX
$PKGNAME: system I have touched. A couple of things have not been implemented, 
$PKGNAME: (a) other - a feature to hold two files in memory (b) error on saving
$PKGNAME: detected, the original ISIS-II would reboot if you attempted to write
$PKGNAME: to a read-only disk. It has even run on UNIX 7 on a PDP-II emulator.
EOF

	ARCH=$(uname -m)
	OSVER=$(. /etc/os-release ; echo $VERSION_ID)

	case "$ARCH" in
		aarch64 | x86_64 )
			;;
		arm* )
			ARCH=arm
			;;
		* )
			ARCH=$(gcc -Q --help=target | grep "\-march=" | while read A B C; do echo $B; break; done)
			;;
	esac
	
	tar --create --owner=0 --group=0 --gzip --file "$PKGNAME-$VERSION-$ARCH-1_slack$OSVER.tgz" -C data/root . -C .. usr/bin/aedit usr/share/doc/aedit usr/share/man/man1/aedit.1.gz install/slack-desc
fi
