#!/bin/sh -e
#
#  Copyright 2021, Roger Brown
#
#  This file is part of RHB aedit.
#
#  This program is free software: you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation, either version 3 of the License, or (at your
#  option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# $Id: Linux 19 2022-01-12 15:46:43Z rhubarb-geek-nz $
#

cleanup()
{
	rm -rf data rpms rpm.spec
}

umask 022

cleanup

trap cleanup 0

VERSION=$(grep "Id:\ aedit.c" < src/aedit.c | while read A B C D E; do echo $D; done)
HIVERS=$(echo $VERSION / 10000 | bc)
LOVERS=$(echo $VERSION % 10000 | bc)
PWD=`pwd`
ISSLACK=false
ISRPM=false
ISDEB=false

for d in $( . /etc/os-release ; echo $ID $ID_LIKE )
do
	case "$d" in
		debian )
			ISDEB=true
			;;
		fedora | centos | rhel )
			ISRPM=true
			;;
		slackware )
			ISSLACK=true
			;;
	esac
done

mkdir -p data/usr/bin rpms

VERSION="1.1.$HIVERS.$LOVERS"
PKGNAME=aedit

cp aedit data/usr/bin

if $ISDEB
then
	DPKGARCH=$(dpkg --print-architecture)
	SIZE=$(du -sk data/usr/bin/aedit | while read A B; do echo $A; done)
	mkdir data/DEBIAN
	cat > data/DEBIAN/control <<EOF
Package: $PKGNAME
Version: $VERSION
Architecture: $DPKGARCH
Installed-Size: $SIZE
Maintainer: rhubarb-geek-nz@users.sourceforge.net
Section: editors
Priority: extra
Description: Aedit editor
 Text editor based resembling ISIS alter.
 .
EOF

	dpkg-deb --root-owner-group --build data "$PKGNAME"_"$VERSION"_"$DPKGARCH".deb

	rm -rf data/DEBIAN
fi

if $ISRPM
then
	cat > rpm.spec <<EOF
Summary: Aedit editor
Name: aedit
Version: $VERSION
Release: 1
Group: Applications/System
License: GPL
Prefix: /usr

%description
Text editor based on ISIS alter

%files
%defattr(-,root,root)
%attr(755,root,root) /usr/bin/aedit

%clean
EOF

	rpmbuild --buildroot "$PWD/data" --define "_rpmdir $PWD/rpms" --define "_build_id_links none" -bb "$PWD/rpm.spec" 

	find rpms -name "*.rpm" -type f | while read N
	do
		mv "$N" .
	done
fi

if $ISSLACK
then
	mkdir -p data/usr/bin data/install data/root
	cp aedit data/usr/bin
	strip data/usr/bin/aedit

	cat > data/install/slack-desc <<EOF
$PKGNAME: aedit ISIS-II style text editor
$PKGNAME:
$PKGNAME: Text editor based on interface from Intel ISIS-II aedit, which in turn
$PKGNAME: turn was based on its big brother alter. 
$PKGNAME: 
$PKGNAME: This was originally written in the mid 80s on QNX running on an 8088, 
$PKGNAME: with a CBM-64 acting as the console. I have used this on every UNIX
$PKGNAME: system I have touched. A couple of things have not been implemented, 
$PKGNAME: (a) other - a feature to hold two files in memory (b) error on saving
$PKGNAME: detected, the original ISIS-II would reboot if you attempted to write
$PKGNAME: to a read-only disk. It has even run on UNIX 7 on a PDP-II emulator.
EOF

	ARCH=$(uname -m)
	OSVER=$(. /etc/os-release ; echo $VERSION_ID)

	case "$ARCH" in
		aarch64 | x86_64 )
			;;
		arm* )
			ARCH=arm
			;;
		* )
			ARCH=$(gcc -Q --help=target | grep "\-march=" | while read A B C; do echo $B; break; done)
			;;
	esac
	
	tar --create --owner=0 --group=0 --gzip --file "$PKGNAME-$VERSION-$ARCH-1_slack$OSVER.tgz" -C data/root . -C .. usr/bin/aedit install/slack-desc
fi
