#!/bin/sh -e
#
#  Copyright 2021, Roger Brown
#
#  This file is part of RHB aedit
#
#  This program is free software: you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by the
#  Free Software Foundation, either version 3 of the License, or (at your
#  option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# $Id: NetBSD 4 2021-04-18 12:02:33Z rhubarb-geek-nz $
#

VERSION=$(grep "Id:\ aedit.c" < src/aedit.c | while read A B C D E; do echo $D; done)
HIVERS=$(echo $VERSION / 10000 | bc)
LOVERS=$(echo $VERSION % 10000 | bc)
PWD=`pwd`

VERSION="1.1.$HIVERS.$LOVERS"
PKGNAME="aedit-$VERSION.tgz"

cleanup()
{
	rm -rf root meta
}

trap cleanup 0

cleanup

mkdir -p root/usr/bin meta

cp aedit root/usr/bin
strip root/usr/bin/aedit

(
	echo HOMEPAGE=http://rhbaedit.sf.net
	echo MACHINE_ARCH=$(uname -p)
	echo OPSYS=$(uname -s)
	echo OS_VERSION=$(uname -r)
	echo PKGTOOLS_VERSION=$(pkg_info -V)
) > meta/BUILD_INFO

cat > meta/CONTENTS << EOF
@name aedit-$VERSION
usr/bin/aedit
EOF

echo "Text Editor based on Intel ISIS-II aedit" >"meta/COMMENT"

cat >"meta/DESC" <<EOF
Text editor based on interface from Intel ISIS-II aedit, which in turn was based on its big brother alter.

This was originally written in the mid 80s on QNX running on an 8088, with a CBM-64 acting as the console.
EOF

pkg_create -v -B meta/BUILD_INFO -c meta/COMMENT -g wheel -u root -d meta/DESC -I / -f meta/CONTENTS -p root -F gzip "$PKGNAME"
