#!/bin/sh -e
#
#  Copyright 2021, Roger Brown
#
#  This file is part of RHB aedit
#
#  This program is free software: you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation, either version 3 of the License, or (at your
#  option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# $Id: OpenBSD 51 2023-12-19 13:39:26Z rhubarb-geek-nz $
#

VERSION=$(grep "Id:\ aedit.c" < src/aedit.c | while read A B C D E; do echo $D; done)
HIVERS=$(echo $VERSION / 256 | bc)
LOVERS=$(echo $VERSION % 256 | bc)
PWD=`pwd`

VERSION="1.1.$HIVERS.$LOVERS"
PKGNAME="aedit-$VERSION.tgz"

cleanup()
{
	rm -rf root meta unsigned aedit-$VERSION-pkg.sec
}

trap cleanup 0

cleanup

mkdir -p root/usr/bin meta unsigned 

cp aedit root/usr/bin
strip root/usr/bin/aedit

cat > meta/CONTENTS << EOF
usr/bin/aedit
EOF

echo "Text Editor based on Intel ISIS-II aedit" >"meta/COMMENT"

cat >"meta/DESC" <<EOF
Text editor based on interface from Intel ISIS-II aedit, which in turn was based on its big brother alter.

This was originally written in the mid 80s on QNX running on an 8088, with a CBM-64 acting as the console.
EOF

COMMENT="Text Editor based on Intel ISIS-II aedit"
MACHINE_ARCH=$(uname -p)
HOMEPAGE=http://aedit.sf.net
MAINTAINER=rhubarb-geek-nz@users.sourceforge.net
FULLPKGPATH=editors/aedit
FTP=yes

pkg_create \
		-A "$MACHINE_ARCH"\
		-d meta/DESC \
		-D "COMMENT=$COMMENT" \
		-D "HOMEPAGE=$HOMEPAGE" \
		-D "MAINTAINER=$MAINTAINER" \
		-D "FULLPKGPATH=$FULLPKGPATH" \
		-D "FTP=$FTP" \
		-f meta/CONTENTS \
		-B root \
		-p / \
		"unsigned/$PKGNAME"

signify -G -n -c "aedit-$VERSION package" -s aedit-$VERSION-pkg.sec -p aedit-$VERSION-pkg.pub

pkg_sign -s signify2 -s aedit-$VERSION-pkg.sec -o . -S unsigned
