#!/bin/sh -e
#
#  Copyright 2021, Roger Brown
#
#  This file is part of RHB aedit
#
#  This program is free software: you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation, either version 3 of the License, or (at your
#  option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# $Id: QNX 81 2024-01-28 21:33:48Z rhubarb-geek-nz $
#

VERSION=$(grep "Id:\ aedit.c" < src/aedit.c | while read A B C D E; do echo $D; done)
MAJVERS=1
MINVERS=$(echo $VERSION / 256 + 1 | bc)
BLDVERS=$(echo $VERSION % 256 | bc)
PWD=$(pwd)

VERSION="$MAJVERS.$MINVERS.$BLDVERS"
PKGNAME=aedit

trap 'rm aedit.qpg' 0

cat >aedit.qpg <<EOF
<QPG:Generation>
   <QPG:Options>
      <QPG:User unattended="no" verbosity="2" listfiles="yes"/>
      <QPG:Defaults type="qnx_package"/>
      <QPG:Source></QPG:Source>
      <QPG:Release number="+"/>
      <QPG:Build></QPG:Build>
      <QPG:FileSorting strip="yes"/>
      <QPG:Package targets="combine"/>
      <QPG:Repository generate="yes"/>
      <QPG:FinalDir></QPG:FinalDir>
      <QPG:Cleanup></QPG:Cleanup>
   </QPG:Options>

   <QPG:Responsible>
      <QPG:Company></QPG:Company>
      <QPG:Department></QPG:Department>
      <QPG:Group></QPG:Group>
      <QPG:Team></QPG:Team>
      <QPG:Employee></QPG:Employee>
      <QPG:EmailAddress></QPG:EmailAddress>
   </QPG:Responsible>

   <QPG:Values>
      <QPG:Files>
         <QPG:Add file="aedit" install="/usr/bin/" tos="qnx6"/>
      </QPG:Files>

      <QPG:PackageFilter>
         <QPM:PackageManifest>
            <QPM:PackageDescription>
               <QPM:PackageType>Application</QPM:PackageType>
               <QPM:FileVersion>2.6</QPM:FileVersion>
               <QPM:DateCode>4bbe8479</QPM:DateCode>
            </QPM:PackageDescription>

            <QPM:ProductDescription>
               <QPM:ProductName>aedit</QPM:ProductName>
               <QPM:ProductIdentifier>aedit</QPM:ProductIdentifier>
               <QPM:VendorName>Public</QPM:VendorName>
               <QPM:VendorInstallName>public</QPM:VendorInstallName>
               <QPM:AuthorName>Roger Brown</QPM:AuthorName>
               <QPM:ProductDescriptionShort>Text Editor based on Intel ISIS-II aedit</QPM:ProductDescriptionShort>
               <QPM:ProductDescriptionLong>Text editor based on interface from Intel ISIS-II aedit, which in turn was based on its big brother alter. This was originally written in the mid 80s on QNX running on an 8088, with a CBM-64 acting as the console.</QPM:ProductDescriptionLong>
            </QPM:ProductDescription>

            <QPM:ReleaseDescription>
               <QPM:ReleaseVersion>$VERSION</QPM:ReleaseVersion>
               <QPM:ReleaseUrgency>Medium</QPM:ReleaseUrgency>
               <QPM:ReleaseStability>Stable</QPM:ReleaseStability>
               <QPM:ReleaseNoteMinor>General release</QPM:ReleaseNoteMinor>
               <QPM:ReleaseNoteMajor>General release</QPM:ReleaseNoteMajor>
               <QPM:ReleaseCopyright>GNU General Public License</QPM:ReleaseCopyright>
            </QPM:ReleaseDescription>

            <QPM:ContentDescription>
               <QPM:ContentTopic xmlmultiple="true">Text Editing and Processing/Text Editors</QPM:ContentTopic>
               <QPM:ContentKeyword>aedit</QPM:ContentKeyword>
               <QPM:DisplayEnvironment xmlmultiple="true">Console</QPM:DisplayEnvironment>
               <QPM:TargetAudience xmlmultiple="true">User</QPM:TargetAudience>
               <QPM:TargetOS>qnx6</QPM:TargetOS>
            </QPM:ContentDescription>
         </QPM:PackageManifest>
      </QPG:PackageFilter>

      <QPG:PackageFilter proc="none" target="none">
         <QPM:PackageManifest></QPM:PackageManifest>
      </QPG:PackageFilter>

      <QPG:PackageFilter proc="x86" target="none">
         <QPM:PackageManifest></QPM:PackageManifest>
      </QPG:PackageFilter>
   </QPG:Values>
</QPG:Generation>
EOF

packager -u aedit.qpg
