#!/bin/sh -e
#
#  Copyright 2021, Roger Brown
#
#  This file is part of RHB aedit.
#
#  This program is free software: you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by the
#  Free Software Foundation, either version 3 of the License, or (at your
#  option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# $Id: SunOS 78 2024-01-23 08:20:36Z rhubarb-geek-nz $
#

VERSION=$(grep "Id: aedit.c" < src/aedit.c | while read A B C D E; do echo $D; done)
MAJVERS=1
MINVERS=$(echo $VERSION / 256 + 1 | bc)
BLDVERS=$(echo $VERSION % 256 | bc)
PWD=$(pwd)
VERSION="$MAJVERS.$MINVERS.$BLDVERS"
APPNAME=aedit
PKGNAME=RHBaedit
DESCRIPTION="Text Editor based on Intel ISIS-II aedit"
INTDIR="$PWD/data"
PKGROOT="$INTDIR/pkgroot"
PKGTMP="$INTDIR/pkgtmp"

cleanup()
{
	rm -rf "$INTDIR"
}

umask 022

cleanup

trap cleanup 0

mkdir -p "$PKGROOT/bin" "$PKGROOT/share/man/man1" "$PKGTMP"

cp "$APPNAME" "$PKGROOT/bin"
cp "$APPNAME.1" "$PKGROOT/share/man/man1"

ARCH_P=$(uname -p)
ARCH_M=$(uname -m)

PKGFILE="$PKGNAME-$VERSION-$ARCH_P.pkg"

rm -rf "$PKGFILE"

(
	echo "ARCH=\"$ARCH_P.$ARCH_M\""
	echo "CATEGORY=\"utility\""
	echo "NAME=\"$DESCRIPTION\""
	echo "PKG=\"$PKGNAME\""
	echo "VERSION=\"$VERSION\""
	echo "BASEDIR=\"/usr\""
) >"$INTDIR/pkginfo"

(
	echo i pkginfo
	echo f none "bin/$APPNAME" 0755 root root
	echo f none "share/man/man1/$APPNAME.1" 0444 root root
) >"$INTDIR/prototype"

pkgmk -o -r "$PKGROOT" -d "$PKGTMP" -f "$INTDIR/prototype" "$PKGNAME"

touch "$PKGFILE"

pkgtrans -s "$PKGTMP" "$PKGFILE" "$PKGNAME"

pkginfo -l -d "$PKGFILE"
